# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: deead622ef120869342cb32430f11edebfb65950bc78faa2f193aa3a097dc731bbc17dfd202b9d626029763efb79d8bc7f12d83b3cf19a3e768b66424c6f0a14

test:
  secret_key_base: d526c0dc1b4832da698d8b3691f86d1bf4c2260a029b81e128898fb288dd8321aec30b04b618fba37be02b757f3f56e57543690bfb76bb71427d08d2789f46c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
